### PR TITLE
Bug fixes for alignment with ALOS SLCs. 

### PR DESCRIPTION
**Pull request by ericlindsey**
2 changes: fix typo PRM to PRF in align_ALOS_SLC.csh, and update name of LED files in align_batch_ALOS_SLC.csh.

### CODE REVIEW

**Comment by ericlindsey** [comment]
Seems like this code might never have worked properly. Is there a different workflow I should be using for these data instead?

**Comment by Xiaohua-Eric-Xu** [comment]
We are turning to the universal p2p_processing.csh. The idea is to use config file to control which part to be processed and then essentially form a batch processing chain.

**Comment by ericlindsey** [comment]
Thanks! Does that script work already for the ALOS SLC data? ASF have now started pushing out the complete ALOS archive (2006-2011) for the whole world but only in this format, so I expect renewed interest in this workflow.

**Comment by Xiaohua-Eric-Xu** [comment]
Yes, we had that for a while now. ALOS_SLC is processed the same way as ALOS2_SLC in this script. If you are doing secondary alignment, you may need to tweak a bit to split the alignment step and do it twice with xcorr/resamp using p2p_processing.csh.

**Comment by Xiaohua-Eric-Xu** [comment]
Here's an example http://topex.ucsd.edu/gmtsar/tar/ALOS_SLC_L1.1.tar.gz

**Comment by ericlindsey** [comment]
Thank you! Got it!

**Pull request merged**
