### PR TITLE
Install additional "py" and "sh" directories to manage Python and Bas…

### PR DESCRIPTION
**Pull request by mobigroup**
Added new directories to organize new scripts.

### CODE REVIEW

**Comment by Xiaohua-Eric-Xu** [comment]
I don't think currently there is a sh or py directory in the distribution yet.

**Comment by mobigroup** [comment]
There are no the directories and that's the problem. You've placed [fetchOrbit.py](https://github.com/mobigroup/gmtsar/blob/master/gmtsar/csh/fetchOrbit.py) and [fit_planar_trend.py](https://github.com/mobigroup/gmtsar/blob/master/gmtsar/csh/fit_planar_trend.py) to csh directory.

**Comment by mobigroup** [comment]
About the sh directory: I'd add scripts to initiate Google/Amazon Cloud VM instance with installed GMTSAR and dependencies. For now it looks to complicated to launch the ready to use environment and run the processing. 
It looks like to
```
gcloud compute instances create \
    --project "..." \
    --tags gmtsar gmtsar \
    --boot-disk-size 32 --boot-disk-type=pd-ssd \
    --machine-type n2-standard-2 --zone=asia-southeast2-a \
    --image-family=debian-10 --image-project=debian-cloud \
    --service-account=... \
    --scopes https://www.googleapis.com/auth/cloud-platform \
    --metadata-from-file startup-script=GMTSAR.install.debian10.sh
```
where the init script GMTSAR.install.debian10.sh (and it's suitable for Amazon EC2 too, of course). See the SBAS processing scripts here: https://github.com/mobigroup/gmtsar/tree/master/gmtsar/sh

**Comment by Xiaohua-Eric-Xu** [comment]
@dsandwell do we want to build more directories of scripts in gmtsar?

**Comment by mobigroup** [comment]
Actually, some additional Python scripts would be helpful, see https://github.com/mobigroup/gmtsar/tree/master/gmtsar/py
These scripts allow to use GMTSAR even on free Google Colab cloud environment without any dazzle with GMTSAR installation and configuration. See some Google Colab examples here: https://github.com/mobigroup/gmtsar And sure, every example can be downloaded and used locally on Linux/MacOS (including M1/M2 apple silicon hosts) or on Google Cloud/Amazon EC2 instances.

**Pull request closed without merging**
