### PR TITLE
Create snaphu_interp_custom.sh

### PR DESCRIPTION
**Pull request by SteffanDavies**
@Xiaohua-Eric-Xu This rewrite of the snaphu_interp.csh script in bash will allow the user to pass custom flags to snaphu as an argument. 

Note that defining a region is now mandatory, and passing 0/0/0/0 will unwrap entire scene (same as passing no region in previous script).

Snaphu flags can be passed as optional fourth argument as a string (ex: "--tile 4 4 200 200 --nproc 16 -S"). If no fourth argument is passed, then it runs like default.

Consider merging if you find this useful.

### CODE REVIEW

**Comment by Xiaohua-Eric-Xu** [comment]
Great. At some point, we may want to write a wrapper for these scripts so all flags could be read in just once. Once we have that I could help make them options in the config file for step-5.

**Comment by SteffanDavies** [comment]
> Great. At some point, we may want to write a wrapper for these scripts so all flags could be read in just once. Once we have that I could help make them options in the config file for step-5.

So you want to set all flags for snaphu a priori in batch_tops_config of in snaphu config?

Flags will overwrite config file parameters.

You can also point to more than one config file and latter will overwrite first snaphu config values.

If you have a clear idea of how you want to do it, the rest is simple enough. However keep in mind snaphu configuration might require adjustment if not ideal.

**Comment by SteffanDavies** [comment]
It is also possible to define parameters through a global variable, which is the case for sbas_parallel OMP_NUM_THREADS. 

However I don't really like this option personally.

**Comment by Xiaohua-Eric-Xu** [comment]
It'll be like other parameters which will be piped to the new snaphu script (wrapper) and the used as flags inside.

**Pull request merged**
