### PR TITLE
snaphu_interp.csh: apply landmask to correlation grid

### PR DESCRIPTION
**Pull request by chintals**
Apply landmask to corr grd to weed out pixels that are above the corr threshold and are in the water regions

### CODE REVIEW

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @chintals, the landmasking of coherence does not affect phase unwrapping as the phase gets replaced to all zeros in water regions.

**Comment by chintals** [comment]
@Xiaohua-Eric-Xu That is what I though as well, but after running nearest_grid, the phase_tmp.grd  has constant phase values (replacing zeros). Could you confirm that the phase_tmp.grd after nearest grid step is still all zeros for you?

**Comment by Xiaohua-Eric-Xu** [comment]
@chintals I am sorry somehow I thought this is snaphu.csh. snaphu_interp.csh will replace all NaNs to their nearest neighbors. phase_tmp.grd should not be nans in the ocean area. However, to save time, there is a 300 search radius set for nearest_grid. So likely there will be zeros left in the water region after nearest_grid. An alternative to nearest_grid (which is slow large chunk of area to interpolate) is the Matlab griddata.

**Comment by chintals** [comment]
Yes, so in some of my runs, I get corr vals greater than the set corr threshold and while landmask is applied to the phase and interpolated to nearest neighbors, the input corr grid is only masked with corr threshold and may still contain corr vals above threshold that are in water regions and is factored in unwrapping. And post snaphu, we mask the final unwrap phase with landmask again which gets rid of the high corr unwrapped phase on the water.

I guess my edit would eliminate processing any high corr values (above set threshold) on water regions during snaphu unwrapping.

 The edit I proposed would eliminate that issue.

**Comment by chintals** [comment]
To clarify, I know SNAPHU phase input cannot handle NANs, so we do nearest neighbor.

Another issue (or not issue) is masked  corr.in has NANs in. I was under the impression that masked corr.in would be masked values almost zero (say 1e-06) or 0, but we directly pass corr.in with NANs (?) to SNAPHU. We can see that by viewing corr_tmp.grd.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @chintals, NaN and zero are the same for snaphu I think. 

I guess I am still a bit confused. What I don't really understand is that since phase is masked, why bother masking coherence as it only acts as weights for the optimization? I thought the 0-norm snaphu will only play with the residues (i.e. minimum length connection). If you don't really need the solution on water, it probably does not matter masking or not the coherence on water. It may help me better understand the reason behind if you have an example to show the effect of this extra masking.

**Comment by chintals** [comment]
Hi @Xiaohua-Eric-Xu give me a couple of days for the example. Maybe you are correct and the final unwrapped solution might not be different.

**Comment by Xiaohua-Eric-Xu** [comment]
Thanks for taking the effort on this!

**Comment by chintals** [comment]
@Xiaohua-Eric-Xu So the test case I ran with and without applying landmask to corr.in show no difference, except for few pixels in the land/water boundary.
preview of the unwrapped phase after snaphu (prior to apply stacked corr mask or landmask)
image
difference of the unwrapped phase after snaphu (without landmask to corr - with landmask to corr)
image

The ranges/histograms are essentially same as well. 

You can close this pull request. This was a good test to figure out if there would be any difference i the solution if the AOI has significant water region in the scene.
image

**Comment by Xiaohua-Eric-Xu** [comment]
Thanks a lot for taking the effort on making the test.

**Pull request closed without merging**
