### PR TITLE
Add python utilities pop_config and p2p_processing.

### PR DESCRIPTION
**Pull request by dunyuliu**
1. Add python utility pop_config.
2. Add python utility p2p_processing.
3. Add software environment file gmtsar_env.yml for anaconda build.
4. Tested with p2p_processing RS2 RS220110515 RS220110819

### CODE REVIEW

**Comment by mobigroup** [comment]
@dunyuliu GMTSAR Docker image is already available on DockerHub: https://hub.docker.com/u/mobigroup Python library PyGMTSAR allows to run InSAR processing scripts as Google Colab or local or cloud notebooks and as console scripts, see for details https://github.com/mobigroup/gmtsar

**Comment by Xiaohua-Eric-Xu** [comment]
@mobigroup, we are asking Dunyu to help us build python modules (not wrapper) for the next stage of development. We noticed many students at our annual short course does not use shell scripting anymore so ... 

Wrapping C-Shells with Python will work but will not provide flexibility for Python users for their own development if you don't expect them to learn shell. And of course conversion to Python will enhance the readability of the scripts. We'll not change any of the c-modules and will keep the shell scripts.

And many simple math will be done directly in Python without writing to temporary files which will reduce disk I/O.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu That’s great but there is the question: what is the goal? Students often don’t have powerful hardware and a lot of disk space too and the ability to run all the processing on Google Colab is the target for PyGMTSAR. How about to read all the data from the Sentinel-1 geotiff files on the fly without merging them to new ones and creating almost the same but raw binary files for the processing? It would allow to processes on Google Colab 5+ full stitched scenes or perform SBAS analysis on dozens of interferometry pairs. Really, I’m glad to know you are ready to rewrite all the old shell scripts to new ones (that’s valuable independently of the programming language)… at the same time I tried to do it before (on bash) and I didn’t find significant advantages. Ok, let’s imagine that students use a modern 64 cores desktop but could the new Python GMTSAR version allow to process a single interferogram 64 times faster? How about an interactive SBAS processing in 1.5 hours lecture time? For now, Gamma-based cloud processing on Alaska Satellite Facility for 1000 scenes monthly is much more accessible then local GMTSAR processing I think. At the end of the day, GMTSAR potential is amazing and as I show it we can process a huge amount of data even on Apple Air laptop. Please think a bit far then just your shell scripts upgrading for better balance between your work time and the expected results.

**Comment by Xiaohua-Eric-Xu** [comment]
I think not just for students. Soon we'll be asked to do everything in the cloud as well since the next game changer will be NISAR, which will produce much much more data than Sentinel. Yes we can still download to local for processing but that will cost a lot of time compared to processing on the cloud where the data's located. This is actually our current project under the support of NSF, i.e. make the software compatible with cloud computing and python based scripts, environment and image are all part of it. The major advantage of Python is readability and simplified computation. I know you work a lot on such development and any suggestion is welcome.

**Comment by mobigroup** [comment]
That’s great you are already working on NISAR support. Actually, all binary tools are problematic for distributed cloud computing. PyGMTSAR still uses phasediff and phasefilt binaries and that is problematic for many cases like to parallel and distributed processing (from the original geotif files). For the best solution we need to have a complete lazy pipeline when a small image area can be processed just in seconds. And I can say Python code for distributed parallel computing is not well readable but very complicated and tricky… single-core shell scripts are much more readable of course. Right now I’m working on a workaround to process multiple subswaths for stitched scenes on Google Colab and it’s really weird and produces some unpredictable issues.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu And I’m surprised why do you speak about shell scripts wrapping?

> Wrapping C-Shells with Python will work but will not provide flexibility for Python users for their own development if you don't expect them to learn shell.

Although I saw someones but there are no successful between them I think… actually, the complexity just multiplied. For now, PyGMTSAR uses only 12 GMTSAR binaries and these are not adopted for parallel and distributed computing. So that would be better to rewrite all of them on Python at the end.

**Comment by Xiaohua-Eric-Xu** [comment]
I see. So you basically replaced shell with Python for connecting the modules. I guess that's our goal as well, except we want to keep the shell functions separate, so that they can be called individually.

**Comment by mobigroup** [comment]
Yes, right. As you remember I’ve sent a set of patches to do it and that’s easy to use all the binary tools from Python now. The problems are large images processing (it should be multicore) and disk space consumption. Using limited resources like to home laptop or Google Colab environment (108 GB disk space available in total and limited processing time) we have no ability to process NISAR data in the future.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Could you estimate the required RAM, CPU, disk space for a single scene NISAR interferogram processing using your code? For the reference, Google Colab provides 2 CPU cores, 12 GB RAM and 108 GB disk space, is it enough? Also, would it be possible to download the images as separate ones or even by bursts without the full scene archive downloading and unpacking? GitHub Actions  for CI tests provide 14 GB disk space (I think we can obtain 24 GB by system cleanup) and 7 GB RAM plus 2 CPU cores (14 GB RAM plus 3 CPU cores for MacOS runners) and it would be great to have ability to process one or more bursts on them. And in the case your resources requirements are higher where is the bottleneck?

**Comment by Xiaohua-Eric-Xu** [comment]
For now I only processed NISAR simulated data which is ~5GB each, so I just dumped everything into memory for reading and writing the data. I am not sure about the exact size (or frame) of NISAR data so could not provide an accurate estimate. If in any case there is a RAM limit, I could change the reading/writing to line by line, though later processing may still try to read everything into memory in case a very high-resolution is set for processing. And in any case that is not enough, we still have the (as promised) geocoded SLC which is (as expected) smaller size.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu I have completed lazy and parallel Python realization for Gaussian (multi-looking) and Goldstein filters. As expected, it works faster than your binaries while loading data by overlapping chunks has ~30% overhead. That’s more accurate due to real multi-looking with signal-noise ratio enhancement instead of GMTSAR decimation and single-pass Gaussian filtering instead of two sequential passes (theoretically, that’s the same but not when you use very cropped convolution window). In case you are going to process much larger data some GMTSAR optimizations required I think. The first problem is algorithmic because you apply slow two-dimensional Gaussian filter vs two fast single-dimensional ones (as I’ve noted before), the second - your convolution tool uses decimations for speed up while code vectorization is much more effective (actually, decimation is useless fir speed up here but it’s useless for noise reduction). As the result, GMTSAR CI test is about 2 times slower than the same PyGMTSAR test (even the more, it limits the memory consumption for 2GB per process). This is the example notebook to illustrate the new features: https://github.com/mobigroup/gmtsar/blob/pygmtsar/todo/phasefilt_lazy.ipynb

I suppose after replacing GMTSAR phasediff by lazy Python realization we will be able to process NISAR data even on a basic Apple Air laptop. And, of course, that’s possible to add PS analysis too (the lazy function to read binary SLC files is already included in PyGMTSAR code, see the linked notebook). I hope the advantages of the code modernization are obvious now.

**Comment by Xiaohua-Eric-Xu** [comment]
> real multi-looking with signal-noise ratio enhancement

Are you sure that "real multi-looking" enhances SNR at all spectrum? A non-overlapping running mean (multi-looking) will enhance noise at Nyquist, which is the primary reason why Gaussian+decimation is used in GMTSAR, as no matter how you wrap the spectrum, the frequency response looks like Gaussian. 

image

> actually, decimation is useless fir speed up here but it’s useless for noise reduction

I am not sure what you mean here...Gaussian filtering is useless for noise reduction?

**Comment by mobigroup** [comment]
Downscaling is two-steps operation. Gaussian filtering is antialiasing filtering and it removes too high frequencies. The point is Nyquist frequency changes due to downscaling. The second step is averaging. 4 pixels average reduces dispersion 2 times (proportional to 1/sqrt(number_of_samples)) so it greatly enhances signal-noise ratio. You missed this step because decimating does not enhance signal. Maybe do you imagine neighboring pixels are exactly the same after antialiasing filtering? That’s wrong assumption and it is easy to check. If you think multi-looking does not use antialiasing filtering it does not make sense - if it is so, the realization is incorrect. All of that are really basics of signal processing engineering.

**Comment by Xiaohua-Eric-Xu** [comment]
Are you saying multi-looking is antialiasing?

**Comment by mobigroup** [comment]
(Pre-)multi-looking filter is antialiasing filter. GMTSAR gaussian filtering is antialiasing filtering. Multi-looking is averaging.

**Pull request closed without merging**
